INSERT INTO public.permission (id, name, title, content_type_id) VALUES (1, 'add_permission', 'Can add permission', 1);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (2, 'change_permission', 'Can change permission', 1);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (3, 'delete_permission', 'Can delete permission', 1);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (4, 'add_group', 'Can add group', 2);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (5, 'change_group', 'Can change group', 2);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (6, 'delete_group', 'Can delete group', 2);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (7, 'add_content-type', 'Can add content type', 3);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (8, 'change_content-type', 'Can change content type', 3);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (9, 'delete_content-type', 'Can delete content type', 3);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (10, 'add_user', 'Can add user', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (11, 'change_user', 'Can change user', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (12, 'delete_user', 'Can delete user', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (13, 'read_user', 'Can read user', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (14, 'read_group', 'Can read group', 2);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (15, 'read_permission', 'Can read permission', 1);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (16, 'read_content-type', 'Can read content type', 3);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (17, 'change_profile', 'Can change profile', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (18, 'read_themes-page', 'Can read themes page', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (19, 'read_account-page', 'Can read account page', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (20, 'read_profile-frame', 'Can read profile frame', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (21, 'read_admin-page', 'Can read admin page', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (22, 'read_groups-frame', 'Can read groups frame', 4);
INSERT INTO public.permission (id, name, title, content_type_id) VALUES (23, 'read_users-frame', 'Can read users frame', 4);